Repository coding-blocks/CBOnlineApp, pull requests merged in 2019-05, with the labels that each got.

#165 feat: add info for all centres
  app/src/main/java/com/codingblocks/cbonlineapp/activities/AboutActivity.kt
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#167 fix: fixed drawer item status behaviour
  app/src/main/res/menu/activity_home_drawer.xml
Labels: fix

#177 feat: integrate Koin with ViewModels
  app/build.gradle
  app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
  app/src/main/java/com/codingblocks/cbonlineapp/Modules.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/HomeActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/MyCourseActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/VideoPlayerActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/MyCoursesViewHolder.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionDetailsAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/VideosDoubtsAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/VideosNotesAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/BaseDao.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/CourseRunDao.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/InstructorDao.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/models/DbModels.kt
  app/src/main/java/com/codingblocks/cbonlineapp/extensions/LiveDataExtensions.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/AllCourseFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/CourseContentFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/HomeFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/MyCoursesFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/Constants.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/VdoPlayerControlView.java
  app/src/main/java/com/codingblocks/cbonlineapp/util/VideoUtils.java
  app/src/main/java/com/codingblocks/cbonlineapp/util/VideoUtils.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/CourseViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/HomeViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/MyCourseViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoViewModel.kt
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/Clients.kt
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/models/APIModel.kt
  onlineapi/src/test/java/com/codingblocks/onlineapi/api/OnlineJsonApiAuthenticatedTest.kt
  onlineapi/src/test/java/com/codingblocks/onlineapi/api/OnlineJsonApiPublicTest.kt
Labels: feature

#160 feat: Added Layout Screen for Quiz Result.
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/QuizFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/QuizResultFragment.kt
  app/src/main/res/drawable/circle.xml
  app/src/main/res/drawable/tick_inside_circle.png
  app/src/main/res/layout/fragment_quiz_result.xml
Labels: feature

#192 fix: viewpager goes to first index after each cycle
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/HomeFragment.kt
Labels: fix

#194 fix: add Snaphelper to Batches Recycler View
  app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt
Labels: fix

#197 feat: add shimmer to course content sections
  app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionsDataAdapter.kt
  app/src/main/res/drawable/ic_up_arrow.xml
  app/src/main/res/layout/item_skeleton_section_card.xml
Labels: feature

#199 Fixed incorrect quiz attempt time
  app/src/main/java/com/codingblocks/cbonlineapp/extensions/LiveDataExtensions.kt
Labels: BOUNTY 50

#210 Improved Quiz Flow
  app/src/main/java/com/codingblocks/cbonlineapp/activities/QuizActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/ViewPagerAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/AboutQuizFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/QuizFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/QuizResultFragment.kt
  app/src/main/res/animator/slide_in_right.xml
  app/src/main/res/animator/slide_out_left.xml
  app/src/main/res/layout/fragment_quiz_result.xml
Labels: BOUNTY 100, BOUNTY 300

#212 feat: integrate one signal
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
  app/src/main/java/com/codingblocks/cbonlineapp/DownloadStarter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/Modules.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/HomeActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/NotificationsActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/SplashActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/CarouselSliderAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/NotificationsAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionDetailsAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/commons/NotificationsDiffCallback.kt
  app/src/main/java/com/codingblocks/cbonlineapp/commons/RecyclerViewCallbacks.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/AppDatabase.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/BaseDao.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/NotificationDao.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/models/DbModels.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/CourseContentFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/ui/HomeFragmentUi.kt
  app/src/main/java/com/codingblocks/cbonlineapp/ui/NotificationCardUi.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/DoubleClickListener.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/DownloadStarter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/MediaUtils.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/OneSignalHandlers.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/ProgressBarAnimation.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/VideoUtils.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/ZoomOutPageTransformer.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/NotificationViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/widgets/ViewPagerCustomDuration.kt
  app/src/main/res/drawable/ic_double_tick_indicator.xml
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/drawable/ic_notification_active.xml
  app/src/main/res/layout/activity_notifications.xml
  app/src/main/res/menu/home.xml
  app/src/main/res/menu/home_notifications.xml
  app/src/main/res/menu/notification_menu.xml
  app/src/main/res/values/strings.xml
  build.gradle
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/api/OnlineJsonApi.kt
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/models/APIModel.kt
Labels: feature

#220 Added correct skeleton layout for quiz
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/AboutQuizFragment.kt
  app/src/main/res/layout/item_skeleton_quiz.xml
Labels: BOUNTY 100

#225 refactor: HomeActivityViewModel Added and more lint fixes
  app/build.gradle
  app/src/main/java/com/codingblocks/cbonlineapp/Modules.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/HomeActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/FileUtils.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/NetworkUtils.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/HomeActivityViewModel.kt
  app/src/main/res/values/strings.xml
Labels: chore, refactor

#224 feat: Add leaderboard on course consumption page
  app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
  app/src/main/java/com/codingblocks/cbonlineapp/Modules.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/MyCourseActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/LeaderboardListAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/MyCoursesViewHolder.kt
  app/src/main/java/com/codingblocks/cbonlineapp/commons/LeaderboardDiffCallback.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/LeaderboardFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/OverviewFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/ui/LeaderboardCardUi.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/LeaderboardViewModel.kt
  app/src/main/res/drawable/ic_leaderboard.xml
  app/src/main/res/layout/fragment_leaderboard.xml
  app/src/main/res/layout/leader_board_list.xml
  app/src/main/res/layout/leaderboard_header.xml
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/models/RESTAPIModel.kt
Labels: feature
