Repository coding-blocks/CBOnlineApp, pull requests merged in 2019-06, with the labels that each got.

#240 refactor: fixes to MVVM Architecture followed by the app
  app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
  app/src/main/java/com/codingblocks/cbonlineapp/Modules.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/HomeActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/SettingsActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/VideoPlayerActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/AllCoursesViewHolder.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/CourseDataAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/EndlessPagerAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/MyCoursesViewHolder.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionDetailsAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionsDataAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/VideosDoubtsAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/VideosNotesAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/AppDatabase.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/ContentDao.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/AllCourseFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/AnnouncementsFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/CourseContentFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/HomeFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/MyCoursesFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/VideoDoubtFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/fragments/VideoNotesFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/services/DownloadService.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/Constants.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/MediaUtils.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/NetworkUtils.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/AnnouncementsViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/CourseViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/HomeActivityViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/HomeViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/MyCourseViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/NotificationViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/SettingsViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoPlayerViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/VideoViewModel.kt
  app/src/main/res/values/strings.xml
Labels: chore, refactor

#248 fix: travis build
  app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
  app/src/main/java/com/codingblocks/cbonlineapp/URLRouterActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/extensions/LangUtilsExtensions.kt
Labels: fix

#273 fix: Video Player now maintains the ratio, neverless the device ratio
  app/src/main/java/com/codingblocks/cbonlineapp/activities/VideoPlayerActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/HomeViewModel.kt
Labels: fix

#271 feat: add worldCup
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
  app/src/main/java/com/codingblocks/cbonlineapp/URLRouterActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/ThrowableActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/adapters/CarouselSliderAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/database/AppDatabase.kt
  app/src/main/java/com/codingblocks/cbonlineapp/extensions/LiveDataExtensions.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/OneSignalHandlers.kt
  app/src/main/java/com/codingblocks/cbonlineapp/util/PreferenceHelper.kt
  app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/HomeActivityViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/widgets/GradientTextView.kt
  app/src/main/java/com/codingblocks/cbonlineapp/widgets/ToggleButtonGroupTableLayout.kt
  app/src/main/res/drawable-xhdpi/banner_mobile.jpg
  app/src/main/res/drawable-xhdpi/bannner.jpg
  app/src/main/res/drawable-xhdpi/dailywinner.png
  app/src/main/res/drawable-xhdpi/flag_placeholder.png
  app/src/main/res/drawable-xhdpi/right.png
  app/src/main/res/drawable-xhdpi/wrong.png
  app/src/main/res/drawable/button_background_throwable.xml
  app/src/main/res/drawable/gradient_outline.xml
  app/src/main/res/drawable/gradient_theme_worlcup.xml
  app/src/main/res/drawable/ic_left_arrow.xml
  app/src/main/res/layout/activity_course.xml
  app/src/main/res/layout/activity_throwable.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/Clients.kt
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/api/OnlineJsonApi.kt
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/api/OnlineRestApi.kt
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/models/APIModel.kt
  onlineapi/src/test/java/com/codingblocks/onlineapi/api/OnlineJsonApiPublicTest.kt
Labels: feature

#280 fix: empty screen when back pressed on aboutquiz fragment
  app/src/main/java/com/codingblocks/cbonlineapp/activities/QuizActivity.kt
  app/src/main/java/com/codingblocks/cbonlineapp/activities/ThrowableActivity.kt
Labels: fix

#285 fix: video crash when youtube video
  app/src/main/java/com/codingblocks/cbonlineapp/activities/VideoPlayerActivity.kt
  onlineapi/src/test/java/com/codingblocks/onlineapi/api/OnlineJsonApiAuthenticatedTest.kt
  onlineapi/src/test/java/com/codingblocks/onlineapi/api/OnlineRestApiAuthenticatedTest.kt
Labels: fix
