Repository coding-blocks/CBOnlineApp, pull requests merged in 2020-05, with the labels that each got.

#785 fix: Prof pic through social
  app/src/main/java/com/codingblocks/cbonlineapp/profile/ProfileActivity.kt
Labels: fix

#805 fix: WhatsApp card displaying for empty link
  app/src/main/java/com/codingblocks/cbonlineapp/mycourse/overview/OverviewFragment.kt
Labels: fix

#814 fix: LinearLayout to properly display 'View all'
  app/src/main/res/layout/fragment_dashboard_explore.xml
Labels: fix

#703 Pip functionality
  app/src/main/AndroidManifest.xml
  app/src/main/assets/fonts/NunitoSans-Regular.ttf
  app/src/main/java/com/codingblocks/cbonlineapp/library/LibraryViewFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/mycourse/content/CourseContentFragment.kt
  app/src/main/java/com/codingblocks/cbonlineapp/mycourse/player/VideoPlayerActivity.kt
Labels: on hold

#820 feat: Leaderboard for course overview
  .idea/misc.xml
  app/src/main/java/com/codingblocks/cbonlineapp/di/Modules.kt
  app/src/main/java/com/codingblocks/cbonlineapp/mycourse/MyCourseRepository.kt
  app/src/main/java/com/codingblocks/cbonlineapp/mycourse/MyCourseViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/mycourse/leaderboard/LeaderboardViewModel.kt
  app/src/main/java/com/codingblocks/cbonlineapp/mycourse/overview/LeaderBoardListAdapter.kt
  app/src/main/java/com/codingblocks/cbonlineapp/mycourse/overview/LeaderBoardViewHolder.kt
  app/src/main/java/com/codingblocks/cbonlineapp/mycourse/overview/OverviewFragment.kt
  app/src/main/res/layout/fragment_overview.xml
  app/src/main/res/layout/item_course_leaderboard.xml
  app/src/main/res/values/strings.xml
  onlineapi/src/main/kotlin/com/codingblocks/onlineapi/api/OnlineRestApi.kt
Labels: feature
